function setPsthGlobalSettings
    global psthStatsSettings
    psthStatsSettings = struct(...
        'compressToList', false, ...
        'compressToSparse', true, ...
        'storeLogOfPvalues', true, ...
        'storeUnassignedValuesAs', 'zeros', ...
        'nudge0pval_amt', 1e-100, ...
        'statsPrecision', 'double', ...
        'ospPhCompressFcn', 'mean', ...
        'cphSplitTime_ms', 70, ...
        'bkgrSkip_ms', 250 ...
    );
end

% Notes: regarding storing of psthStats for each window, we had a couple of options. We wanted to
% store all possible combinations... (fill in text later)